### ISSUE TITLE
你好哈，1.2版本的typecho，获取文章的 api 出问题了哈。

### ISSUE THREAD

**Issue by mrjucn** [moefront/typecho-plugin-Restful#22]
Argument 1 passed to Utils\Markdown::convert() must be of the type string, null given, called in D:\phpstudy_pro\WWW\typecho\var\Widget\Base\Contents.php on line 915

**Comment by LamaGE** [comment]
同样的问题，看源码，死活没搞明白，是1.2的更新什么内容了吗？

**Comment by LamaGE** [comment]
升级到 PHP 7.2 后将给 Typecho 代码带来如下变化：

类名全部由下划线风格转向反斜线的 namespace 风格

// 之前的代码
new Typecho_Widget_Helper_Form();

// 之后的代码
use Typecho\Widget\Helper\Form;

new Form();
我看到了这个Typecho 1.2.0的这个说明，但是不知道怎么改，plugin.php里很多。不知道怎么下手，不会PHP。
